title: mihica khare
author: "Mihica Khare"

theme: minima

base_url: ""
repository: pheidias1137/pheidias1137.github.io

# Minima social links
github_username: pheidias1137
linkedin_username: mihica-khare-440079312


# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%d-%m-%Y"

# Minima: custom header links
header_pages:
  - _pages/blog.md
  - _pages/projects.md
  - _pages/bookshelf.md
  - _pages/about.md
  

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
